### ISSUE TITLE
which branch is fork from bitcoin

### ISSUE THREAD

**Issue by dgu0323** [fractal-bitcoin/fractal#1]
I would like to research the changes Fractal made to the Bitcoin repository. I compared the master branches of the Bitcoin and Fractal repositories and found many differences. Could you please let me know from which branch of Bitcoin Fractal was forked?

**Comment by proteanx** [comment]
> I would like to research the changes Fractal made to the Bitcoin repository. I compared the master branches of the Bitcoin and Fractal repositories and found many differences. Could you please let me know from which branch of Bitcoin Fractal was forked?

I didn't work on fractal but it's forked from the v24.0.1 tag (master branch)
