### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by cekongsb** [fractal-bitcoin/fractal#15]
**The following error occurs when I perform a make compilation**
```
test/fuzz/chain.cpp: In function ‘void chain_fuzz_target(FuzzBufferType)’:
test/fuzz/chain.cpp:36:71: error: no matching function for call to ‘CDiskBlockIndex::GetBlockHeader()’
   36 |     const CBlockHeader block_header = disk_block_index->GetBlockHeader();
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from test/fuzz/chain.cpp:5:
./chain.h:265:18: note: candidate: ‘CBlockHeader CBlockIndex::GetBlockHeader(const Consensus::Params&) const’
  265 |     CBlockHeader GetBlockHeader(const Consensus::Params& consensusParams) const;
      |                  ^~~~~~~~~~~~~~
./chain.h:265:18: note:   candidate expects 1 argument, 0 provided
make[2]: *** [Makefile:15980: test/fuzz/fuzz-chain.o] Error 1
make[2]: Leaving directory '/opt/fractal/src'
make[1]: *** [Makefile:19105: all-recursive] Error 1
make[1]: Leaving directory '/opt/fractal/src'
make: *** [Makefile:824: all-recursive] Error 1

```

**Comment by Grin0502** [comment]
Same error

**Comment by Grin0502** [comment]
I solved with adding new function without any parameters of GetBlockHeader function.

**Comment by Grin0502** [comment]
src/chain.h
![image](https://github.com/user-attachments/assets/fa31e311-8c17-42a9-9aee-7fee36d9a40f)
src/chain.cpp
![image](https://github.com/user-attachments/assets/3117bfff-2e24-4969-bf0f-738e8d26dc97)

after that "make check" again.
There are no issues and solved.

**Comment by cekongsb** [comment]
thanks a lot

**Comment by seoseo29** [comment]
> большое спасибо

Пришлите измененные файлы, что то у меня не получается

**Comment by seoseo29** [comment]
error
make[2]: *** No rule to make target 'test/fuzz/signet.cpp', needed by 'test/fuzz/fuzz-signet.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
script/descriptor.cpp: In function ‘miniscript::NodeRef<Key> miniscript::internal::Parse(Span<const char>, const Ctx&) [with Key = unsigned int; Ctx = {anonymous}::KeyParser]’:
script/descriptor.cpp:1227:26: warning: ‘<anonymous>’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 1227 |         if (!pk) return {};
      |                          ^
make[2]: Leaving directory '/home/pool/fractal/src'
make[1]: *** [Makefile:19103: all-recursive] Error 1
make[1]: Leaving directory '/home/pool/fractal/src'
make: *** [Makefile:821: all-recursive] Error 1

**Comment by www222fff** [comment]
You can ignore fuzz build

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/30/2024 02:52 |
| To | fractal-bitcoin/fractal ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | Re: [fractal-bitcoin/fractal] Compilation failure (Issue #15) |

error
make[2]: *** No rule to make target 'test/fuzz/signet.cpp', needed by 'test/fuzz/fuzz-signet.o'. Stop.
make[2]: *** Waiting for unfinished jobs....
script/descriptor.cpp: In function ‘miniscript::NodeRef miniscript::internal::Parse(Span, const Ctx&) [with Key = unsigned int; Ctx = {anonymous}::KeyParser]’:
script/descriptor.cpp:1227:26: warning: ‘’ may be used uninitialized in this function [-Wmaybe-uninitialized]
1227 | if (!pk) return {};
| ^
make[2]: Leaving directory '/home/pool/fractal/src'
make[1]: *** [Makefile:19103: all-recursive] Error 1
make[1]: Leaving directory '/home/pool/fractal/src'
make: *** [Makefile:821: all-recursive] Error 1

**Comment by seoseo29** [comment]
> You can ignore fuzz build

flag
./configure --disable-fuzz ?
